/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Network.Client;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import klydar_list.Data;
import static klydar_list.Data.db;
import sun.applet.Main;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import sun.awt.image.ImageCache;

/**
 *
 * @author Sheko
 */
public class chat extends javax.swing.JFrame {

    /**
     * Creates new form chat
     */
    static chat old_frame=null;
    
    static String chat_style="<!DOCTYPE html><html><head>"
            + "<style>body{background-color:#36393e;}"
            + "#send{width:100%;border-style:none;background-color:#4080ff;"
            + "color:white;font-size:11px;padding:0px;margin-left:10px;margin-right:200;margin-top:4px;text-align:center}"
            + "#recv{width:100%;border-style: none;background-color:#f1f0f0;"
            + "color:#73787d;font-size:11px;padding:0px;margin-right:10px;margin-left:200;margin-top:4px;text-align:center;}"
            + "#send_time{font-size:9px;color:white;margin:0px;text-align:right;padding-right:4px;padding-bottom:2px;}"
            + "#recv_time{font-size:9px;color:#73787d;margin:0px;text-align:right;padding-right:4px;padding-bottom:2px;}"
            + "#sender_name{font-size:9px;color:white;margin:0px;text-align:left;padding-left:4px;padding-top:0px;}"
            + "#recv_name{font-size:9px;color:#73787d;margin:0px;text-align:left;padding-left:4px;padding-top:0px;}</style></head>";
    static String messages_style = "";
    static String body="";
    public chat() {
        if(old_frame==null)
        {
            old_frame=this;
            initComponents();
        }
        else
        {
            old_frame.dispose();
            old_frame=this;
            initComponents();
        }
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chat_scroll_panel = new javax.swing.JScrollPane();
        chat = new javax.swing.JEditorPane();
        message = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chat");

        chat_scroll_panel.setBorder(null);

        chat.setEditable(false);
        chat.setBackground(new java.awt.Color(54, 57, 62));
        chat.setBorder(null);
        chat.setContentType("text/html"); // NOI18N
        chat.setText("");
        chat_scroll_panel.setViewportView(chat);

        message.setBackground(new java.awt.Color(204, 204, 204));
        message.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        message.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        message.setBorder(null);
        message.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                messageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                messageFocusLost(evt);
            }
        });
        message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 89, 178));
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(54, 57, 62));
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(118, 238, 198));
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(198, 226, 255));
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 193, 193));
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(message)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 301, Short.MAX_VALUE))
            .addComponent(chat_scroll_panel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chat_scroll_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageFocusGained
        // TODO add your handling code here:
        message.setText("");
        message.setFont(new Font("Tahom",Font.PLAIN,17));
        message.setForeground(new Color(100,100,100));
    }//GEN-LAST:event_messageFocusGained

    private void messageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageFocusLost
        // TODO add your handling code here:
        message.setFont(new Font("Tahom",Font.PLAIN,14));
        message.setForeground(new Color(120,120,120));
        message.setText("Type a message...");
    }//GEN-LAST:event_messageFocusLost

    private void messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageActionPerformed
        // TODO add your handling code here:
        send_message(message.getText(),Login.Uname);
        Send_message_ToAll(message.getText());//send message to all clients in the network ya 7lbo2ah
        message.setText(""); // ya 7lbo2ah
        
    }//GEN-LAST:event_messageActionPerformed
    //****************************Send messages to all users************************
    public void Send_message_ToAll(String message){
        String query = "select ip,port from user_settings where username !='"+Login.Uname+"'";
        String ip;
        int port;
        Client clients;
        try {
            ResultSet result = Data.db.select_query(query);
            while(result.next()){
                ip = result.getString("ip");//get the ip from the db
                port = result.getInt("port");//get the port from the db
                if(ip.equals("none")) continue; // skip this ip
                clients = new Client(ip,port);//connect to the other client with ip and port
                clients.send_data(Login.Uname);//send username
                clients.send_data(message);//send message
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Send message to all -> "+ex);
        }
        
    }
    //***************************************************************************
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        change_color(jButton2.getBackground());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        change_color(jButton1.getBackground());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        change_color(jButton3.getBackground());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        change_color(jButton5.getBackground());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        change_color(jButton4.getBackground());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        change_color(jButton6.getBackground());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        try
        {
             String imgsrc = 
            chat.class.getClassLoader().getSystemResource("1.jpg").toString();
            Calendar cal = Calendar.getInstance();
            messages_style +="<div id='send'><p id='sender_name'>sheko</p><img src='"+imgsrc+"'><p id='send_time'>"+cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+"</p></div>";
            body = "<body>"+messages_style+"</body></html>";
            chat.setText(chat_style+body);
            Send_message_ToAll(":");
        }
        catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
         try
        {
             String imgsrc = 
            chat.class.getClassLoader().getSystemResource("2.png").toString();
            Calendar cal = Calendar.getInstance();
            messages_style +="<div id='send'><p id='sender_name'>sheko</p><img src='"+imgsrc+"'><p id='send_time'>"+cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+"</p></div>";
            body = "<body>"+messages_style+"</body></html>";
            chat.setText(chat_style+body);
            Send_message_ToAll("::");
        }
        catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
         try
        {
             String imgsrc = 
            chat.class.getClassLoader().getSystemResource("3.png").toString();
            Calendar cal = Calendar.getInstance();
            messages_style +="<div id='send'><p id='sender_name'>sheko</p><img src='"+imgsrc+"'><p id='send_time'>"+cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+"</p></div>";
            body = "<body>"+messages_style+"</body></html>";
            chat.setText(chat_style+body);
            Send_message_ToAll(":::");
        }
        catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jLabel3MousePressed
    //*********************************************************************
    public void change_color(Color new_color)
    {
        String hex_color = String.format("#%02x%02x%02x", new_color.getRed(), new_color.getGreen(), new_color.getBlue());  
        chat_style="<!DOCTYPE html><html><head>"
            + "<style>body{background-color:"+hex_color+";}"
            + "#send{width:100%;border-style:none;background-color:#4080ff;"
            + "color:white;font-size:11px;padding:0px;margin-left:10px;margin-right:200;margin-top:4px;text-align:center}"
            + "#recv{width:100%;border-style: none;background-color:#f1f0f0;"
            + "color:#73787d;font-size:11px;padding:0px;margin-right:10px;margin-left:200;margin-top:4px;text-align:center;}"
            + "#send_time{font-size:9px;color:white;margin:0px;text-align:right;padding-right:4px;padding-bottom:2px;}"
            + "#recv_time{font-size:9px;color:#73787d;margin:0px;text-align:right;padding-right:4px;padding-bottom:2px;}"
            + "#sender_name{font-size:9px;color:white;margin:0px;text-align:left;padding-left:4px;padding-top:0px;}"
            + "#recv_name{font-size:9px;color:#73787d;margin:0px;text-align:left;padding-left:4px;padding-top:0px;}</style></head>";
        body = "<body>"+messages_style+"</body></html>";
        chat.setText(chat_style+body);
    }
    //*********************************************************************
    public void send_message(String mes , String User)
    {
        try
        {
            Calendar cal = Calendar.getInstance();
            messages_style +="<div id='send'><p id='sender_name'>"+User+"</p>"+mes+"<p id='send_time'>"+cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+"</p></div>";
            body = "<body>"+messages_style+"</body></html>";
            chat.setText(chat_style+body);
        }
        catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null,e);
        }
    }
    //*********************************************************************
    public static void rec_message(String mes , String User)
    {
        try
        {
            Calendar cal = Calendar.getInstance();
            //check if it emotions
            if(mes.equals(":"))
            {
                String imgsrc = 
                chat.class.getClassLoader().getSystemResource("1.jpg").toString();
                messages_style += "<div id='recv'><p id='recv_name'>"+User+"</p><img src='"+imgsrc+"'><p id='recv_time'>"+cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+"</p></div>";
            }
            else if(mes.equals("::"))
            {
                String imgsrc = 
                chat.class.getClassLoader().getSystemResource("2.png").toString();
                messages_style += "<div id='recv'><p id='recv_name'>"+User+"</p><img src='"+imgsrc+"'><p id='recv_time'>"+cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+"</p></div>";
            }
            else if(mes.equals(":::"))
            {
                String imgsrc = 
                chat.class.getClassLoader().getSystemResource("3.png").toString();
                messages_style += "<div id='recv'><p id='recv_name'>"+User+"</p><img src='"+imgsrc+"'><p id='recv_time'>"+cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+"</p></div>";
            }
            else
            {
                messages_style += "<div id='recv'><p id='recv_name'>"+User+"</p>"+mes+"<p id='recv_time'>"+cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+"</p></div>";
            }
            body = "<body>"+messages_style+"</body></html>";
            chat.setText(chat_style+body);
        }
        catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null,e);
        }
    }
    //*********************************************************************
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JEditorPane chat;
    private javax.swing.JScrollPane chat_scroll_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField message;
    // End of variables declaration//GEN-END:variables
}
