/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import klydar_list.Data;
import klydar_list.DatabaseConstants;

/**
 *
 * @author Klydar
 */
public class Check_in_out extends javax.swing.JFrame {

    /**
     * Creates new form Check_in_out
     */
    public Check_in_out() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scan_code = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        scan_code.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        scan_code.setForeground(new java.awt.Color(41, 58, 74));
        scan_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        scan_code.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Scan Here ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(41, 58, 74)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 58, 74), 2))); // NOI18N
        scan_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                scan_codeFocusGained(evt);
            }
        });
        scan_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scan_codeActionPerformed(evt);
            }
        });
        scan_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                scan_codeKeyReleased(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(41, 58, 74));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Check In - Out");

        jButton1.setBackground(new java.awt.Color(41, 58, 74));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check Out All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scan_code)
            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(218, 218, 218))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(scan_code, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scan_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scan_codeActionPerformed
        // TODO add your handling code here:
        try {
            set_cme(scan_code.getText());
            scan_code.setText("");
            scan_code.requestFocus();
        } catch (Exception e) {
            scan_code.setText("");
        }
    }//GEN-LAST:event_scan_codeActionPerformed

    private void scan_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_scan_codeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_scan_codeKeyReleased

    private void scan_codeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_scan_codeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_scan_codeFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
//            String datetime = get_datetime();
            String query = "update lists SET in_out=0,out_time =NOW(),CME=CEIL(TIME_TO_SEC(TIMEDIFF(out_time,in_time))/(60))+CME WHERE in_out = 1";
            klydar_list.Klydar_List.data_list.VUpdate_Data(query);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    //get in function working with the one who entered SESSION TO calculate cme
    public void set_cme(String user_id) {
        try {

            String query = "select in_out from " + DatabaseConstants.tableName + " where id=" + user_id + "";
            ResultSet result = Data.db.select_query(query);
            String datetime = "";
            datetime = get_datetime();
            if (result.next()) {
                if (result.getInt("in_out") == 0) {

                    query = "UPDATE lists SET in_out=1,in_time=NOW(),attendees=1 where id=" + user_id + "";
                    klydar_list.Klydar_List.data_list.VUpdate_Data(query);
                } else {
                    query = "update lists SET in_out=0,out_time =NOW(),CME=CEIL(TIME_TO_SEC(TIMEDIFF(out_time,in_time))/(60))+CME WHERE id =" + user_id + "";

                    klydar_list.Klydar_List.data_list.VUpdate_Data(query);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    //SELECT DATE_FORMAT(in_time,'%H:%i:%s') TIMEONLY from lists where id =5393
    public String get_datetime() {
        java.util.Date dt = new java.util.Date();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String currentTime = sdf.format(dt);
        return currentTime;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField scan_code;
    // End of variables declaration//GEN-END:variables
}
