/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import klydar_list.Data;
import klydar_list.DatabaseConstants;
import klydar_list.correct_frame;

/**
 *
 * @author Talaat
 */
public class update_Data extends javax.swing.JFrame {

    /**
     * Creates new form update_Data
     */
    public String updated_id="";
    public update_Data() {
        initComponents();
    }
    public update_Data(ResultSet data) {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        try
        {
            name_field.setText(data.getString("name"));
            mob_field.setText(data.getString("mobile"));
            mail_field.setText(data.getString("email"));
            sponsor_field.setText(data.getString("sponsor"));
            instituation.setText(data.getString("Institution"));
            profession.setText(data.getString("profession"));
            address.setText(data.getString("address"));
            type_list.setSelectedItem(data.getString("type"));
            specality_list.setSelectedItem(data.getString("speciality"));
            updated_id=data.getString("id");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mob_field = new javax.swing.JTextField();
        name_field = new javax.swing.JTextField();
        mail_field = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        sponsor_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        instituation = new javax.swing.JTextField();
        profession = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        specality_list = new javax.swing.JComboBox();
        type_list = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Name");

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Mobile");

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Email");

        mob_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mob_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mob_field.setBorder(null);
        mob_field.setInheritsPopupMenu(true);
        mob_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mob_fieldActionPerformed(evt);
            }
        });
        mob_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mob_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mob_fieldFocusLost(evt);
            }
        });

        name_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name_field.setBorder(null);
        name_field.setInheritsPopupMenu(true);
        name_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                name_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_fieldFocusLost(evt);
            }
        });

        mail_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mail_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mail_field.setBorder(null);
        mail_field.setInheritsPopupMenu(true);
        mail_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mail_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mail_fieldFocusLost(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        sponsor_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sponsor_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sponsor_field.setText("Individual");
        sponsor_field.setBorder(null);
        sponsor_field.setInheritsPopupMenu(true);
        sponsor_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sponsor_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sponsor_fieldFocusLost(evt);
            }
        });

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Sponsor");

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("institution");

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Profession");

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Address");

        instituation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        instituation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        instituation.setBorder(null);
        instituation.setInheritsPopupMenu(true);
        instituation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                instituationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                instituationFocusLost(evt);
            }
        });
        instituation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instituationActionPerformed(evt);
            }
        });

        profession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profession.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        profession.setBorder(null);
        profession.setInheritsPopupMenu(true);
        profession.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                professionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                professionFocusLost(evt);
            }
        });

        address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.setBorder(null);
        address.setInheritsPopupMenu(true);
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });

        specality_list.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        specality_list.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Radiology", "Radiotherapy", "Research", "Surgical-Oncology", "Clinical-Pharmacy", "Gyne-oncology", "Nursing", "Palliative-Care", "Pathology" }));
        specality_list.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Speciality", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        type_list.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        type_list.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Chairperson", "Speaker", "Attendance", "Moderator", "Panelist", "Media", "Sponsor", "Organizer" }));
        type_list.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        type_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_listActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(238, 238, 238));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(profession, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instituation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sponsor_field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mail_field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mob_field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(type_list, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(specality_list, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(179, 179, 179))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specality_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mob_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mail_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sponsor_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instituation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profession, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mob_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mob_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mob_fieldActionPerformed

    private void mob_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mob_fieldFocusGained
        // TODO add your handling code here:
        mob_field.setBorder(new LineBorder(Data.white_blue, 2));
    }//GEN-LAST:event_mob_fieldFocusGained

    private void mob_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mob_fieldFocusLost
        // TODO add your handling code here:
        mob_field.setBorder(new LineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_mob_fieldFocusLost

    private void name_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_fieldFocusGained
        // TODO add your handling code here:
        name_field.setBorder(new LineBorder(Data.white_blue, 2));
    }//GEN-LAST:event_name_fieldFocusGained

    private void name_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_fieldFocusLost
        // TODO add your handling code here:
        name_field.setBorder(new LineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_name_fieldFocusLost

    private void mail_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mail_fieldFocusGained
        // TODO add your handling code here:
        mail_field.setBorder(new LineBorder(Data.white_blue, 2));
    }//GEN-LAST:event_mail_fieldFocusGained

    private void mail_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mail_fieldFocusLost
        // TODO add your handling code here:
        mail_field.setBorder(new LineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_mail_fieldFocusLost

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try 
        {
            String query = "UPDATE "+DatabaseConstants.tableName+" SET name='"+name_field.getText()+"',mobile='"+mob_field.getText()+"',"
                    +"email='"+mail_field.getText()+"',sponsor='"+sponsor_field.getText()+"',Institution='"+instituation.getText()+"',"
                    + "profession='"+profession.getText()+"',address='"+address.getText()+"' where id ="+updated_id+"";
            Data.db.updata_query(query);
            done_update("Updated successfully");
            
        }//end try
        catch (NumberFormatException e) {
            design.set_alert_message(jTextField1, "Check Mobile Number");
        }catch (Exception exx) {
            design.set_alert_message(jTextField1, "Invalid Data");
        }
    }//GEN-LAST:event_updateActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        done_update();

    }//GEN-LAST:event_BackActionPerformed
    public void done_update(String text){//close frame the display the scan frame
        dispose();
        scan_update_frame suf = new scan_update_frame(text);
        suf.setVisible(true);
    }
    public void done_update(){//close frame and dispaly the scan frame with confirmation message
        dispose();
        scan_update_frame suf = new scan_update_frame();
        suf.setVisible(true);
    }
    private void sponsor_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sponsor_fieldFocusGained
        // TODO add your handling code here:
        sponsor_field.setBorder(new LineBorder(Data.white_blue, 2));
    }//GEN-LAST:event_sponsor_fieldFocusGained

    private void sponsor_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sponsor_fieldFocusLost
        // TODO add your handling code here:
        sponsor_field.setBorder(new LineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_sponsor_fieldFocusLost

    private void instituationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_instituationFocusGained
        // TODO add your handling code here:
        instituation.setBorder(new LineBorder(Data.white_blue, 2));
    }//GEN-LAST:event_instituationFocusGained

    private void instituationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_instituationFocusLost
        // TODO add your handling code here:
        
        instituation.setBorder(new LineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_instituationFocusLost

    private void professionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_professionFocusGained
        // TODO add your handling code here:
        
        profession.setBorder(new LineBorder(Data.white_blue, 2));
    }//GEN-LAST:event_professionFocusGained

    private void professionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_professionFocusLost
        // TODO add your handling code here:
        
        profession.setBorder(new LineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_professionFocusLost

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        // TODO add your handling code here:
        
        address.setBorder(new LineBorder(Data.white_blue, 2));
    }//GEN-LAST:event_addressFocusGained

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        // TODO add your handling code here:
        
        address.setBorder(new LineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_addressFocusLost

    private void type_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_listActionPerformed

    private void instituationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instituationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instituationActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField address;
    private javax.swing.JTextField instituation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mail_field;
    private javax.swing.JTextField mob_field;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField profession;
    private javax.swing.JComboBox specality_list;
    private javax.swing.JTextField sponsor_field;
    private javax.swing.JComboBox type_list;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
