/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klydar_list;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Klydar
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    static Data ref;
    public AddUser(Data s) {
        initComponents();
        setLocationRelativeTo(null);
        ref = s;
        name_field.requestFocus();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mob_field = new javax.swing.JTextField();
        name_field = new javax.swing.JTextField();
        mail_field = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sponsor_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add User");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Name");

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Mobile");

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Email");

        mob_field.setBackground(new java.awt.Color(204, 204, 204));
        mob_field.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mob_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mob_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mob_fieldActionPerformed(evt);
            }
        });

        name_field.setBackground(new java.awt.Color(204, 204, 204));
        name_field.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        name_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mail_field.setBackground(new java.awt.Color(204, 204, 204));
        mail_field.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mail_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(51, 51, 51));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        sponsor_field.setBackground(new java.awt.Color(204, 204, 204));
        sponsor_field.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sponsor_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sponsor_field.setText("Individual");

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Sponsor");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klydar_list/loading.gif"))); // NOI18N

        add_print.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_print.setForeground(new java.awt.Color(51, 51, 51));
        add_print.setText("Add & Print");
        add_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name_field)
                    .addComponent(mail_field)
                    .addComponent(mob_field, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sponsor_field, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_print, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mob_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sponsor_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(add_print, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mob_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mob_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mob_fieldActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try
        {
            String name=name_field.getText();
            int mob = Integer.parseInt(mob_field.getText());
            String Email = mail_field.getText();
            String Sponsor = sponsor_field.getText();
            if(name.equals("") || Email.equals("") || Sponsor.equals(""))
            {
                JOptionPane.showMessageDialog(null , "Please Fill All Fields :)");
            }//end validate
            else
            {
                String query = "INSERT INTO `lists` (`vip`, `tag`, `conf_id`, `Payment`, `name`, `name_ar`, `type`, `attendees`, `on_site`, `mobile`, `email`, `position`, `address`, `sponsor`, `name_tag`, `bag`, `coffee`, `lunch`, `certificate`, `presence`, `create_time`, `name_tag_time`, `certificate_time`, `bag_time`, `coffee_time`, `lunch_time`, `update_time`, `Profession`, `Institution`, `note`, `country`, `Reg`, `Hotel`, `Session Title`)" +
                    "VALUES ('', '', 0, '', '"+name+"', '', '', 1, 0, '"+mob+"', '"+Email+"', '', '', '"+Sponsor+"', 0, 0, 0, 0, 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '', '', '', '', '', '', '')";
                
                ref.db.updata_query(query);
                JOptionPane.showMessageDialog(null , "Done :)");
                name_field.setText("");
                mob_field.setText("");
                mail_field.setText("");
                
            }
        }//end try
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Check Mobile Number :)");
        }
        catch(Exception exx)
        {
            JOptionPane.showMessageDialog(null, "InValid Data");
        }
    }//GEN-LAST:event_addActionPerformed

    private void add_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_printActionPerformed
        // TODO add your handling code here:
        
try{
            String name=name_field.getText();
            int mob = Integer.parseInt(mob_field.getText());
            String Email = mail_field.getText();
            String Sponsor = sponsor_field.getText();
            if(name.equals("") || Email.equals("") || Sponsor.equals(""))
            {
                JOptionPane.showMessageDialog(null , "Please Fill All Fields","Empty fields",JOptionPane.WARNING_MESSAGE);
            }//end validate
            else
            {
                String query ="INSERT INTO `lists` (`vip`, `tag`, `conf_id`, `Payment`, `name`, `name_ar`, `type`, `attendees`, `on_site`, `mobile`, `email`, `position`, `address`, `sponsor`, `name_tag`, `bag`, `coffee`, `lunch`, `certificate`, `presence`, `create_time`, `name_tag_time`, `certificate_time`, `bag_time`, `coffee_time`, `lunch_time`, `update_time`, `Profession`, `Institution`, `note`, `country`, `Reg`, `Hotel`, `Session Title`)" +
                    "VALUES ('', '', 0, '', '"+name+"', '', '', 1, 0, '"+mob+"', '"+Email+"', '', '', '"+Sponsor+"', 0, 0, 0, 0, 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '', '', '', '', '', '', '')";
                ref.db.updata_query(query);
                query = "select ID from lists where name='"+name+"' && mobile='"+mob+"'";
                ResultSet id_data = ref.db.select_query(query);
                int id =0;
                if(id_data.next()){
                    id = id_data.getInt("ID");
                }
                Directprint print = new Directprint(0);
                print.barcode_generate(Integer.toString(id));
                print.printString(name);
                JOptionPane.showMessageDialog(null , "Done 🙂");
                name_field.setText("");
                mob_field.setText("");
                mail_field.setText("");
                
            }
        }//end try
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Check Mobile Number","Invalid data",JOptionPane.WARNING_MESSAGE);
        }
        catch(Exception exx)
        {
            JOptionPane.showMessageDialog(null, "Invalid Data "+exx,"Invalid User Data",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_add_printActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton add_print;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mail_field;
    private javax.swing.JTextField mob_field;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField sponsor_field;
    // End of variables declaration//GEN-END:variables
}
